kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishListView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    toggle_assign_to_dish,
    DishDetailView,
    CookListView,
    CookDetailView,
    CookUpdateView,
    CookDeleteView,
    CookCreateView,
)

urlpatterns = [
    path("", index, name="index"),
    path("dish-types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path(
        "dish-types/<int:pk>/update",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish-types/<int:pk>/delete",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path("dish/", DishListView.as_view(), name="dish-list"),
    path("dish/create/", DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dish/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path(
        "dish/<int:pk>/toggle-assign/", toggle_assign_to_dish, name="toggle-dish-assign"
    ),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
]

app_name = "kitchen"

restaurant_kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True)

    class Meta:
        ordering = ["username"]

    def __str__(self):
        return f"{self.username} {self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    dish_type = models.ForeignKey(
        DishType, on_delete=models.CASCADE, related_name="dishes"
    )
    cooks = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="dishes")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} (price: {self.price}, dish type: {self.dish_type.name})"

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from kitchen.models import Dish, Cook


class DishForm(forms.ModelForm):
    cookers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishTypesSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name.."}),
    )


class DishesSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name.."}),
    )


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )

    def clean_years_of_experience(self):  # this logic is optional, but possible
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


def validate_years_of_experience(
    years_of_experience,
):  # regex validation is also possible here
    if not int(years_of_experience):
        raise ValidationError("Years of experience should be integer")

    return years_of_experience


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username.."}),
    )


class CookExperienceUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["years_of_experience"]

    def clean_license_number(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import (
    DishTypesSearchForm,
    DishesSearchForm,
    DishForm,
    CookSearchForm,
    CookCreationForm,
    CookExperienceUpdateForm,
)
from kitchen.models import (
    Dish,
    Cook,
    DishType,
)


def index(request):

    num_dish = Dish.objects.count()
    num_cook = Cook.objects.count()
    num_dish_type = DishType.objects.count()

    context = {
        "num_dish": num_dish,
        "num_dish_type": num_dish_type,
        "num_cook": num_cook,
    }

    return render(request, "kitchen/index.html", context=context)


class DishTypeListView(generic.ListView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "kitchen/dish_type_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = DishTypesSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = DishTypesSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    template_name = "kitchen/dish_type_form.html"
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    template_name = "kitchen/dish_type_form.html"
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "kitchen/dish_type_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishListView(generic.ListView):
    model = Dish
    context_object_name = "dish_list"
    template_name = "kitchen/dish_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = DishesSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = Dish.objects.all()
        form = DishesSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class DishDetailView(generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    form_class = DishForm
    template_name = "kitchen/dish_form.html"
    success_url = reverse_lazy("kitchen:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("kitchen:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    context_object_name = "cook_list"
    template_name = "kitchen/cook_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = CookSearchForm(initial={"username": username})

        return context

    def get_queryset(self):
        queryset = Cook.objects.all()
        form = CookSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(username__icontains=form.cleaned_data["username"])

        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookExperienceUpdateForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("")


@login_required
def toggle_assign_to_dish(request, pk):
    cook = Cook.objects.get(id=request.user.id)
    if Dish.objects.get(id=pk) in cook.dishes.all():
        cook.dishes.remove(pk)
    else:
        cook.dishes.add(pk)
    return HttpResponseRedirect(reverse_lazy("kitchen:dish-detail", args=[pk]))

templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete cooke?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: <span style="font-style: italic">{{ cook.username }}</span>
    <a href="{% url 'kitchen:cook-delete' pk=cook.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'kitchen:cook-update' pk=cook.id %}" class="btn btn-secondary link-to-page">
      Update years of experience
    </a>
  </h1>

  <p><strong>First name:</strong> {{ cook.first_name }}</p>
  <p><strong>Last name:</strong> {{ cook.last_name }}</p>
  <p><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>

  <div class="ml-3">
    <h4>Dish</h4>

    {% for dish in cook.dishes.all %}
        <hr>
        <p><strong>Dish:</strong> {{ dish.name }}</p>
        <p><strong>Dish type:</strong> {{ dish.dish_type.name }}</p>
        <p class="text-muted"><strong>Id:</strong> {{dish.id}}</p>

    {% empty %}
      <p>No dishes!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create cooke</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="list-dish-head">
    <div>
        <h1>Cook List</h1>
    </div>
    <div class="add-button">
      <a href="{% url 'kitchen:cook-create' %}">+</a>
    </div>
  </div>
  <div class="search-block">
    <form action="" method="get" class="form-inline">{{ search_form|crispy }}
    <input style="margin-left: 8px" class="btn btn-primary" type="submit" value="search">
    </form>
  </div>

    {% if cook_list %}
      <div class="table-block">
          <table class="table">
      <tr class="table-head">
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Years of experience</th>
      </tr>
    {% for cook in cook_list %}
      <tr>
        <td>{{ cook.id }}</td>
        <td><a href="{{ cook.get_absolute_url }}">{{ cook.username }} {% if user == cook %} (Me){% endif %}</a></td>
        <td>{{ cook.first_name }}</td>
        <td>{{ cook.last_name }}</td>
        <td>{{ cook.years_of_experience }}</td>
      </tr>
    {% endfor %}

    </table>
      </div>
    {% else %}
      <p>There are no cookers in the service.</p>
    {% endif %}
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ dish.name }}
    <a href="{% url 'kitchen:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'kitchen:dish-update' pk=dish.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <p>Price: {{ dish.price }}</p>
  <p>Description: {{ dish.description }}</p>
  <p>Dish Types: ({{ dish.dish_type.name }})</p>
  <h1>
    Cookers

    {% if dish in user.dishes.all %}
      <a href="{% url 'kitchen:toggle-dish-assign' pk=dish.id %}" class="btn btn-danger link-to-page">
        Delete me from this dish
      </a>
    {% else %}
      <a href="{% url 'kitchen:toggle-dish-assign' pk=dish.id %}" class="btn btn-success link-to-page">
        Assign me from this dish
      </a>
    {% endif %}

  </h1>
  <hr>
  <ul>
    {% for cook in dish.cooks.all %}
      <li>{{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }})</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/kitchen/dish_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Dish:</h1>
  <form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="list-dish-head">
    <div>
        <h1>List Dish</h1>
    </div>
    <div class="add-button">
      <a href="{% url 'kitchen:dish-create' %}">+</a>
    </div>
  </div>

  <div class="search-block">
    <form action="" method="get" class="form-inline">
  {{ search_form|crispy }}
    <div>
      <input class="submit-button" style="height: 38px;" type="submit" value="submit">
    </div>
  </form>
  </div>


  {% if dish_list %}
    <div class="table-block">
        <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Dish type</th>
      </tr>
    {% for dish in dish_list %}
      <tr>
        <td>
          <a href="{% url "kitchen:dish-detail" pk=dish.id %}"> {{ dish.id }}</a>
        </td>
        <td>
          {{ dish.name}}
        </td>
        <td>
          {{ dish.description }}
        </td>
        <td>
          {{ dish.price }}
        </td>
        <td>
          {{ dish.dish_type.name }}
        </td>
      </tr>
    {% endfor %}
    </table>

    </div>
  {% else %}
    <p>There are no dish in menu</p>
  {% endif %}

{% endblock %}

templates/kitchen/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish type?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen/dish_type_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Dish Type:</h1>
  <form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <div class="list-dish-head">
    <div>
        <h1>List Dish Types</h1>
    </div>
    <div class="add-button">
        <a href="{% url 'kitchen:dish-type-create' %}">+</a>
    </div>
  </div>
  <div class="search-block">
    <form action="" method="get" class="form-inline">{{ search_form|crispy }}
    <input style="margin-left: 8px" class="btn btn-primary" type="submit" value="search">
    </form>
  </div>

  {% if dish_type_list %}
    <div class="table-block">
        <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    {% for dish_type in dish_type_list %}
      <tr>
        <td>{{ dish_type.id }}</td>
        <td>{{ dish_type.name }}</td>
        <td><a class="custom-link" href="{% url 'kitchen:dish-type-update' pk=dish_type.id%}">UPDATE</a></td>
        <td><a class="custom-link" href="{% url 'kitchen:dish-type-delete' pk=dish_type.id%}">DELETE</a></td>
      </tr>
    {% endfor %}
    </table>
    </div>
  {% else %}
    <p>The are no dish types in dish</p>
  {% endif %}

{% endblock %}

templates/kitchen/index.html
{% extends "base.html" %}

{% block content %}
  <div>
    <div class="header-text">
        <h1>Kitchen Service</h1>
      <p><i>Welcome to Best Restaurant</i></p>
    </div>
    <div class="row library-content">
        <div class="border-right">Total number of dishes: <span>{{ num_dish }}</span></div>
        <div class="border-right">Total number of types of dishes: <span>{{ num_dish_type }}</span></div>
        <div>Total number of cooks: <span>{{ num_cook }}</span></div>
    </div>
  </div>
{% endblock %}